## Acessar o arquivo com a base de dados.
* Acesse o link https://www.kaggle.com/datasets/namespaiva/base-varejo/data
* Faça o download do arquivo base-varejo.zip
* Instalar as bibliotecas Pandas e Numpy, auxiliares ao Python
* Extrair os arquivos da pasta .zip com a base de dados na pasta raiz do projeto

In [ ]:
# Instalar a biblioteca Pandas, auxiliar ao Python
%pip install -q pandas

In [1]:
# Instalar a biblioteca Numpy, auxiliar ao Python
%pip install -q numpy

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Inserir todos os imports necessários para o projeto
import pandas as pd
import numpy as np

In [3]:
# Carregar o arquivo CSV com os dados do projeto
df = pd.read_csv(r"C:\Users\LUIZ HENRIQUE\sesi_senai\mini_projeto_turma05\Base Varejo.csv", sep=";")
df.head() # Exibir as primeiras linhas do DataFrame para verificar se os dados foram carregados corretamente

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,01/02/2019,1000,534,M,4,1,C,67,BEBIDAS,REFRIGERANTE GUARANA,NaN,NaN,NaN,NaN
1,01/02/2019,1000,534,M,4,1,C,70,BEBIDAS,REFRIGERANTE OUTROS,NaN,NaN,NaN,NaN
2,01/02/2019,1000,534,M,4,1,C,178,HIGIENE,LENCO UMEDECIDO,NaN,NaN,NaN,NaN
3,01/02/2019,1000,534,M,4,1,C,4,ALIMENTOS,ABACAXI,NaN,NaN,NaN,NaN
4,01/02/2019,1000,534,M,4,1,C,175,LIMPEZA,LIMPADOR MULTIUSO,NaN,NaN,NaN,NaN

In [ ]:
# Exibir informações sobre o DataFrame, como número de linhas, colunas e tipos de dados
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 830000 entries, 0 to 829999
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATA         830000 non-null  str
 1   CO_ID        830000 non-null  int64
 2   CL_ID        830000 non-null  int64
 3   CL_GENERO    830000 non-null  str
 4   CL_EC        830000 non-null  int64
 5   CL_FHL       830000 non-null  int64
 6   CL_SEG       830000 non-null  str
 7   PR_ID        830000 non-null  int64
 8   PR_CAT       830000 non-null  str
 9   PR_NOME      830000 non-null  str
 10  Unnamed: 10  0 non-null       float64
 11  Unnamed: 11  0 non-null       float64
 12  Unnamed: 12  0 non-null       float64
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(4), int64(5), str(5)
memory usage: 88.7 MB

Através do método df.info() foi possível identificar que há 4 colunas inválidas no DataFrame.
São elas: Unnamed: 10, Unnamed: 11, Unnamed: 12 e Unnamed: 13.

In [7]:
# Retirar as colunas que não serão utilizadas na análise
df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])

In [22]:
# Exibir o número de linhas e colunas do DataFrame após a remoção das colunas inválidas
df.shape

(830000, 10)

In [19]:
# Verificar se há registros ausentes no DataFrame
df.isna().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [20]:
# Verificar se há registros nulos no DataFrame
df.isnull().sum()

DATA         0
CO_ID        0
CL_ID        0
CL_GENERO    0
CL_EC        0
CL_FHL       0
CL_SEG       0
PR_ID        0
PR_CAT       0
PR_NOME      0
dtype: int64

In [ ]:
# Exibir estatísticas descritivas do DataFrame, como média, desvio padrão, valores mínimo e máximo, entre outros
display(df.describe())

              CO_ID          CL_ID          CL_EC        CL_FHL          PR_ID
count  830000.00000  830000.000000  830000.000000  830000.00000  830000.000000
mean   460045.08989     499.595204       2.596911       1.14654     115.051855
std    265465.24754     287.568253       1.170599       1.41696      66.129241
min      1000.00000       1.000000       1.000000       0.00000       1.000000
25%    233117.00000     254.000000       2.000000       0.00000      58.000000
50%    456517.00000     498.000000       3.000000       0.00000     115.000000
75%    690132.00000     746.000000       4.000000       2.00000     172.000000
max    919822.00000    1000.000000       5.000000       4.00000     229.000000

In [ ]:
# Exibir os registros onde a coluna "PR_NOME" possui o valor "N/D" para identificar possíveis inconsistências nos dados
display(df[df["PR_NOME"] == "#N/D"])

,DATA,CO_ID,CL_ID,CL_GENERO,CL_EC,CL_FHL,CL_SEG,PR_ID,PR_CAT,PR_NOME
82,01/02/2019,1078,290,F,1,0,B,107,#N/D,#N/D
223,01/02/2019,1103,957,M,2,3,B,107,#N/D,#N/D
640,01/02/2019,1482,453,F,1,0,B,107,#N/D,#N/D
857,01/02/2019,1683,438,F,1,0,B,107,#N/D,#N/D
917,01/02/2019,1793,608,F,3,0,C,107,#N/D,#N/D
...,...,...,...,...,...,...,...,...,...,...
829528,19/08/2022,919578,567,F,1,0,C,107,#N/D,#N/D
829602,19/08/2022,919626,758,F,3,0,B,107,#N/D,#N/D
829787,19/08/2022,919716,801,M,1,4,B,107,#N/D,#N/D
829829,19/08/2022,919716,801,M,1,4,B,107,#N/D,#N/D
829882,19/08/2022,919770,888,F,4,2,B,107,#N/D,#N/D

Através do método display() acima, foi possível verificar que 3650 linhas do DataFrame possuem registro com valor "#N/D" nas colunas "PR_CAT" e "PR_NOME"

In [30]:
# Descartar os registros onde a coluna "PR_NOME" possui o valor "N/D" para evitar inconsistências na análise
df[["PR_CAT", "PR_NOME"]] = df[["PR_CAT", "PR_NOME"]].replace("#N/D", np.nan)
df = df.dropna(subset=["PR_CAT", "PR_NOME"])

In [32]:
# Exibir o número de linhas e colunas do DataFrame após a remoção dos registros inválidos
df.shape

(826350, 10)